// Code generated by protoc-gen-go. DO NOT EDIT.
// source: msg.proto

package msg

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ReqChat struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	T                    int64    `protobuf:"varint,3,opt,name=t,proto3" json:"t,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqChat) Reset()         { *m = ReqChat{} }
func (m *ReqChat) String() string { return proto.CompactTextString(m) }
func (*ReqChat) ProtoMessage()    {}
func (*ReqChat) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{0}
}

func (m *ReqChat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqChat.Unmarshal(m, b)
}
func (m *ReqChat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqChat.Marshal(b, m, deterministic)
}
func (m *ReqChat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqChat.Merge(m, src)
}
func (m *ReqChat) XXX_Size() int {
	return xxx_messageInfo_ReqChat.Size(m)
}
func (m *ReqChat) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqChat.DiscardUnknown(m)
}

var xxx_messageInfo_ReqChat proto.InternalMessageInfo

func (m *ReqChat) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ReqChat) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *ReqChat) GetT() int64 {
	if m != nil {
		return m.T
	}
	return 0
}

type AckChat struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	T                    int64    `protobuf:"varint,2,opt,name=t,proto3" json:"t,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AckChat) Reset()         { *m = AckChat{} }
func (m *AckChat) String() string { return proto.CompactTextString(m) }
func (*AckChat) ProtoMessage()    {}
func (*AckChat) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{1}
}

func (m *AckChat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AckChat.Unmarshal(m, b)
}
func (m *AckChat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AckChat.Marshal(b, m, deterministic)
}
func (m *AckChat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AckChat.Merge(m, src)
}
func (m *AckChat) XXX_Size() int {
	return xxx_messageInfo_AckChat.Size(m)
}
func (m *AckChat) XXX_DiscardUnknown() {
	xxx_messageInfo_AckChat.DiscardUnknown(m)
}

var xxx_messageInfo_AckChat proto.InternalMessageInfo

func (m *AckChat) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *AckChat) GetT() int64 {
	if m != nil {
		return m.T
	}
	return 0
}

func init() {
	proto.RegisterType((*ReqChat)(nil), "msg.ReqChat")
	proto.RegisterType((*AckChat)(nil), "msg.AckChat")
}

func init() { proto.RegisterFile("msg.proto", fileDescriptor_c06e4cca6c2cc899) }

var fileDescriptor_c06e4cca6c2cc899 = []byte{
	// 115 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcc, 0x2d, 0x4e, 0xd7,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xce, 0x2d, 0x4e, 0x57, 0xb2, 0xe6, 0x62, 0x0f, 0x4a,
	0x2d, 0x74, 0xce, 0x48, 0x2c, 0x11, 0x12, 0xe0, 0x62, 0x2e, 0xcd, 0x4c, 0x91, 0x60, 0x54, 0x60,
	0xd4, 0xe0, 0x0c, 0x02, 0x31, 0x41, 0x22, 0xb9, 0xc5, 0xe9, 0x12, 0x4c, 0x10, 0x91, 0xdc, 0xe2,
	0x74, 0x21, 0x1e, 0x2e, 0xc6, 0x12, 0x09, 0x66, 0x05, 0x46, 0x0d, 0xe6, 0x20, 0xc6, 0x12, 0x25,
	0x4d, 0x2e, 0x76, 0xc7, 0xe4, 0x6c, 0x98, 0x66, 0x90, 0x52, 0x46, 0x34, 0xa5, 0x4c, 0x50, 0xa5,
	0x49, 0x6c, 0x60, 0x3b, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xf5, 0x23, 0xc0, 0xfd, 0x80,
	0x00, 0x00, 0x00,
}
