// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb.pb

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RequestChat struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	T                    int64    `protobuf:"varint,3,opt,name=t,proto3" json:"t,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestChat) Reset()         { *m = RequestChat{} }
func (m *RequestChat) String() string { return proto.CompactTextString(m) }
func (*RequestChat) ProtoMessage()    {}
func (*RequestChat) Descriptor() ([]byte, []int) {
	return fileDescriptor_82312ed5b9cb9aa9, []int{0}
}

func (m *RequestChat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestChat.Unmarshal(m, b)
}
func (m *RequestChat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestChat.Marshal(b, m, deterministic)
}
func (m *RequestChat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestChat.Merge(m, src)
}
func (m *RequestChat) XXX_Size() int {
	return xxx_messageInfo_RequestChat.Size(m)
}
func (m *RequestChat) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestChat.DiscardUnknown(m)
}

var xxx_messageInfo_RequestChat proto.InternalMessageInfo

func (m *RequestChat) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *RequestChat) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *RequestChat) GetT() int64 {
	if m != nil {
		return m.T
	}
	return 0
}

type ResponseChat struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	T                    int64    `protobuf:"varint,2,opt,name=t,proto3" json:"t,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseChat) Reset()         { *m = ResponseChat{} }
func (m *ResponseChat) String() string { return proto.CompactTextString(m) }
func (*ResponseChat) ProtoMessage()    {}
func (*ResponseChat) Descriptor() ([]byte, []int) {
	return fileDescriptor_82312ed5b9cb9aa9, []int{1}
}

func (m *ResponseChat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseChat.Unmarshal(m, b)
}
func (m *ResponseChat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseChat.Marshal(b, m, deterministic)
}
func (m *ResponseChat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseChat.Merge(m, src)
}
func (m *ResponseChat) XXX_Size() int {
	return xxx_messageInfo_ResponseChat.Size(m)
}
func (m *ResponseChat) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseChat.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseChat proto.InternalMessageInfo

func (m *ResponseChat) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *ResponseChat) GetT() int64 {
	if m != nil {
		return m.T
	}
	return 0
}

func init() {
	proto.RegisterType((*RequestChat)(nil), "protocol.RequestChat")
	proto.RegisterType((*ResponseChat)(nil), "protocol.ResponseChat")
}

func init() { proto.RegisterFile("pb.pb", fileDescriptor_82312ed5b9cb9aa9) }

var fileDescriptor_82312ed5b9cb9aa9 = []byte{
	// 125 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x62, 0x2d, 0x48, 0xd2, 0x2b,
	0x48, 0x12, 0xe2, 0x28, 0x28, 0xca, 0x2f, 0xc9, 0x4f, 0xce, 0xcf, 0x51, 0xb2, 0xe7, 0xe2, 0x0e,
	0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x71, 0xce, 0x48, 0x2c, 0x11, 0x12, 0xe0, 0x62, 0x2e, 0xcd,
	0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0x31, 0x41, 0x22, 0xb9, 0xc5, 0xe9, 0x12,
	0x4c, 0x10, 0x91, 0xdc, 0xe2, 0x74, 0x21, 0x1e, 0x2e, 0xc6, 0x12, 0x09, 0x66, 0x05, 0x46, 0x0d,
	0xe6, 0x20, 0xc6, 0x12, 0x25, 0x3d, 0x2e, 0x9e, 0xa0, 0xd4, 0xe2, 0x82, 0xfc, 0xbc, 0xe2, 0x54,
	0x98, 0x09, 0x20, 0xf5, 0x8c, 0x68, 0xea, 0x99, 0xa0, 0xea, 0x93, 0xd8, 0xc0, 0x56, 0x1b, 0x03,
	0x02, 0x00, 0x00, 0xff, 0xff, 0xae, 0x0c, 0x28, 0xde, 0x8a, 0x00, 0x00, 0x00,
}
